project_id = "zasoichsqclaljjhxoop"

[functions.create-mp-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.get-mp-public-key]
verify_jwt = false

[functions.mp-pay]
verify_jwt = false

[functions.expire-orders]
verify_jwt = false
